language: ruby
rvm:
- 2.6.3
services:
  - postgresql
before_install:
  - gem install bundler
  - source .env.test
  - psql -c 'create database elias_test;' -U postgres
before_script:
  - ./bin/migrate
script: bundle exec rspec spec/
